version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.3
    commands:
      - echo 'install'
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'logging in the aws'
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT
    commands:
      - echo 'building image'
      - cp .env.prod .env
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
  post_build:
    on-failure: ABORT
    commands:
      - echo 'docker images ls -a'
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG