version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - DB_HOST: prod-lavarel-api.c1iw46gs6c8m.us-east-2.rds.amazonaws.com
            - DB_PORT: 5432
            - DB_DATABASE: postgres
            - DB_USERNAME: postgres
            - DB_PASSWORD: w2cBD2024
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
        ports:
            - 8080:8080
