version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - database
  # db postgres
  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - './postgresql:/var/lib/postgresql/data'
volumes:
  db-data: ~
